import { Pool } from 'pg';
import { createLogger } from '@ai-commerce-os/shared';
import { StorageClient, StoragePaths } from '@ai-commerce-os/connectors';
import type { TaskJobData } from '@ai-commerce-os/shared';

const log = createLogger('worker');

export async function handleDummyTask(
  job: TaskJobData,
  db: Pool,
  storage: StorageClient,
): Promise<void> {
  const { taskId, storeId } = job;

  log.info({ taskId, storeId }, 'Processing dummy task');

  // 1. Simulate work
  await new Promise((resolve) => setTimeout(resolve, 1000));

  // 2. Create a dummy artifact in S3
  const artifactContent = JSON.stringify({
    taskId,
    storeId,
    generatedAt: new Date().toISOString(),
    message: 'This is a dummy artifact generated by the worker.',
    data: { foo: 'bar', count: 42 },
  }, null, 2);

  const storageKey = StoragePaths.runArtifact(storeId, taskId, 'result.json');

  const uploadResult = await storage.upload({
    key: storageKey,
    body: artifactContent,
    contentType: 'application/json',
  });

  log.info({ taskId, storeId, storageKey, size: uploadResult.size }, 'Artifact uploaded to S3');

  // 3. Save asset reference in DB
  await db.query(
    `INSERT INTO assets (store_id, task_id, name, asset_type, mime_type, size_bytes, storage_key, storage_bucket, actor_type)
     VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)`,
    [
      storeId, taskId, 'result.json', 'run_artifact',
      'application/json', uploadResult.size, storageKey, uploadResult.bucket, 'worker',
    ],
  );

  // 4. Write audit log
  await db.query(
    `INSERT INTO audit_logs (store_id, entity_type, entity_id, action, actor_type, changes, task_id)
     VALUES ($1, 'task', $2, 'processed', 'worker', $3, $2)`,
    [
      storeId, taskId,
      JSON.stringify({ handler: 'dummy', artifact: storageKey, size: uploadResult.size }),
    ],
  );

  log.info({ taskId, storeId }, 'Dummy task completed');
}
